
using UnityEngine;


// control a transform's rotation (with Camera attached) from first person
public class CamController : MonoBehaviour
{
    public GameObject target;
    public float sensitivity = 1f;
    public Texture2D crosshairTexture; // Your custom crosshair texture
    public Camera cam;

    private float verticalRot = 0;
    private float vertRotClamp = 90f;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        if (cam == null)
        {
            cam = Camera.main;
        }
        Cursor.visible = true;
    }

    // Update is called once per frame
    void Update()
    {
        Vector2 mouseInput = new(Input.GetAxis("Mouse X"), Input.GetAxis("Mouse Y"));

        // copying from Unity in Action
        // Vector2 delta = new((mouseInput.x * sensitivity) + target.transform.localEulerAngles.y, -mouseInput.y * sensitivity);
        // target.transform.localEulerAngles = new(delta.y, delta.x, 0);
        verticalRot -= mouseInput.y * sensitivity;
        verticalRot = Mathf.Clamp(verticalRot, -vertRotClamp, vertRotClamp);
        float delta = mouseInput.x * sensitivity;
        float horizRot = target.transform.localEulerAngles.y + delta;

        //target.transform.localEulerAngles = new(verticalRot, horizRot, 0);
        target.transform.localEulerAngles = new(0, horizRot, 0);
        cam.transform.localEulerAngles = new(verticalRot, 0, 0);
    }

    void OnGUI()
    {
        // draw artificial crosshair
        // following code generated by AI Overview
        // Calculate the screen center position

        Vector2 screenCenter = new Vector2(Screen.width / 2, Screen.height / 2);

        // Draw the crosshair at the screen center

        GUI.DrawTexture(new Rect(screenCenter.x - (crosshairTexture.width / 2), screenCenter.y - (crosshairTexture.height / 2), crosshairTexture.width, crosshairTexture.height), crosshairTexture);
    }
}
