using UnityEngine;


// control a transform's rotation (with Camera attached) from first person
public class CamController : MonoBehaviour
{
    public Texture2D crosshairTexture; // Your custom crosshair texture
    [SerializeField] Camera cam;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        if (cam == null)
        {
            cam = Camera.main;
        }
        Cursor.visible = true;
    }

    // Update is called once per frame
    void Update()
    {
        Vector2 mouseInput = new(Input.GetAxis("Mouse X"), Input.GetAxis("Mouse Y"));
        Debug.Log("Mouse Input: " + mouseInput + "(at time " + Time.time + ")");

        // since mouseInput is tracking "change in mouse position",
        // rotate transform around y axis and camera around x axis (I think)

    }

    void OnGUI()
    {
        // draw artificial crosshair
        // following code generated by AI Overview
        // Calculate the screen center position

        Vector2 screenCenter = new Vector2(Screen.width / 2, Screen.height / 2);



        // Draw the crosshair at the screen center

        GUI.DrawTexture(new Rect(screenCenter.x - (crosshairTexture.width / 2), screenCenter.y - (crosshairTexture.height / 2), crosshairTexture.width, crosshairTexture.height), crosshairTexture);
    }
}
