using System.Collections;
using UnityEngine;

[CreateAssetMenu(fileName = "TeleportManager", menuName = "Scriptable Objects/TeleportManager")]

// choose a teleportation 
public class TeleportManager : ScriptableObject
{
    public void SimpleTeleport(GameObject subject, Vector3 destination)
    {
        Debug.Log("[TeleportManager] performing SimpleTeleport!");
        subject.transform.position = destination;
    }

    // usage: StartCoroutine(tm.SmoothTeleport(gameObject, destination, duration));
    public IEnumerator SmoothTeleport(GameObject subject, Vector3 destination, float duration)
    {
        // generated by ChatGPT
        float elapsed = 0f;
        Vector3 startPos = subject.transform.position;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;    // normalize t to be between 0 and 1
            subject.transform.position = Vector3.Lerp(startPos, destination, t);
            yield return null;
        }

        subject.transform.position = destination;
    }
}
